trainer:
  accelerator: auto
  default_root_dir: bns_runs
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val/loss
        mode: min
        save_top_k: 1
        filename: 'ckpt_{epoch:02d}-{step:04d}'
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val/loss
        patience: 5
        mode: min
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
  log_every_n_steps: 1
  max_epochs: 300

data:
  class_path: data.LitBNSDataModule
  init_args:
    hdf5_path: '/n/holystore01/LABS/iaifi_lab/Lab/kyoon/models/BNS/bns_waveforms.hdf5'
    variables: {'chirp_mass', 'mass_ratio', 'total_mass', 'redshift'}
    downsample_factor: 2
    duration: 32
    scale_factor: 1e24
    train_batch_size: 50
    val_batch_size: 50
    test_batch_size: 50

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1e-3

lr_scheduler:
  class_path: torch.optim.lr_scheduler.ExponentialLR
  init_args:
    gamma: 0.99

model:
  class_path: model.LitS4Model
  init_args:
    d_input: 2
    d_output: 8
    d_model: 80
    n_layers: 80
    loss: NLLGaussian
    dropout: 0.02
    lr: 0.005